### ISSUE TITLE
Assign HipChat Server

### ISSUE THREAD

**Issue by dmuess** [dbac2002/sonar-hipchat-plugin#4]
How do i assign the hipchat server to send the message to?

We have our own hipchat server and need the notifications to go to it rather than www.hipchat.com

**Comment by dbac2002** [comment]
I assume, your installation also has the same api available ? Then you can set the "Notification URL template" parameter to your installation.

So instead of 
`https://api.hipchat.com/v2/room/%s/notification?auth_token=%s`
you use
`https://your.server.url/v2/room/%s/notification?auth_token=%s`

This is just a simple guess though.

**Comment by dmuess** [comment]
Yes, but in Sonar where i configure your plugin, Notification URL template is not available
![sonarhipchatplugin](https://cloud.githubusercontent.com/assets/4238457/13707877/7092f8be-e771-11e5-86ce-1b067a8bd5a4.jpg)

Where can i set the url?

**Comment by dbac2002** [comment]
This was done in the pull request https://github.com/dbac2002/sonar-hipchat-plugin/pull/1 - which is currently not released.

I will issue a release start of next week - until then you can clone the repo and see to build the plugin yourself

**Comment by dmuess** [comment]
THank you

**Comment by dbac2002** [comment]
new version available with the pr included
